# Generated by Django 4.1.7 on 2023-02-25 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('copy', models.CharField(blank=True, max_length=255, null=True)),
                ('excerpt', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_copy', models.CharField(blank=True, max_length=255, null=True)),
                ('call', models.CharField(blank=True, max_length=255, null=True)),
                ('appeals', models.CharField(blank=True, max_length=255, null=True)),
                ('checks', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
